const mongoose=require('mongoose');
const {ObjectId}=mongoose.Schema.Types
const UserSchema=mongoose.Schema(
    {
       
        name:{
            type:String,
            required:true           
        },
        emailId:{
            type:String,
            required:true
        },
        phnNo:{
            type:Number,
            required:true
        },
        password:{
            type:String,
            required:true,
        },
        userName:{
            type:String,
            required:true,
        },
        
       followers:[
        {
            type:ObjectId,
            ref:"user"
        }],
        following:[
            {
                type:ObjectId,
                ref:"user"
            }],
        request:[
            {
                type:ObjectId,
                ref:"user"
            }
        ],    
        status:[{
            type:String,
            required:true
        }],
        profile:
            {
            profilePic:
            {
                type:String,
                default:"https://www.w3schools.com/howto/img_avatar.png"
            },
            dob:{
                type:Date,
                default:Date.now
            },
            relationship_status:
            {
                type:String,
                default:"Single"
            },
            location:{
                type:String,
                default:"None"
            },        
            workplace:
            {
                type:String,
                default:"None"
            },
            school_college:
            {
                type:String,
                default:"None"
            }
                }
                 
    });
var userDetails=mongoose.model("user",UserSchema);
module.exports=userDetails;